#!/bin/bash
git add "cli/cli.mjs"
git commit -m "Update cli/cli.mjs: updated cli.mjs for v3 release"
git add "cli/commands/help.js"
git commit -m "Update cli/commands/help.js: updated help.js for v3 release"
git add "cli/commands/show.js"
git commit -m "Update cli/commands/show.js: updated show.js for v3 release"
git add "cli/constants.js"
git commit -m "Update cli/constants.js: updated constants.js for v3 release"
git add "cli/helpers/config.js"
git commit -m "Update cli/helpers/config.js: updated config.js for v3 release"
git add "core/lexer.js"
git commit -m "Update core/lexer.js: updated lexer.js for v3 release"
git add "core/parser.js"
git commit -m "Update core/parser.js: updated parser.js for v3 release"
git add "core/pluginManager.js"
git commit -m "Update core/pluginManager.js: updated pluginManager.js for v3 release"
git add "core/plugins/comment-remover.js"
git commit -m "Update core/plugins/comment-remover.js: updated comment-remover.js for v3 release"
git add "core/plugins/module-system.js"
git commit -m "Update core/plugins/module-system.js: updated module-system.js for v3 release"
git add "core/plugins/quote-escaper.js"
git commit -m "Update core/plugins/quote-escaper.js: updated quote-escaper.js for v3 release"
git add "core/plugins/raw-content-plugin.js"
git commit -m "Update core/plugins/raw-content-plugin.js: updated raw-content-plugin.js for v3 release"
git add "core/plugins/rules-validation-plugin.js"
git commit -m "Update core/plugins/rules-validation-plugin.js: updated rules-validation-plugin.js for v3 release"
git add "core/transpiler.js"
git commit -m "Update core/transpiler.js: updated transpiler.js for v3 release"
git add "debug.js"
git commit -m "Update debug.js: updated debug.js for v3 release"
git add "docs/01.installation.md"
git commit -m "Update docs/01.installation.md: updated 01.installation.md for v3 release"
git add "docs/02.getting-started.md"
git commit -m "Update docs/02.getting-started.md: updated 02.getting-started.md for v3 release"
git add "docs/03.syntax.md"
git commit -m "Update docs/03.syntax.md: updated 03.syntax.md for v3 release"
git add "docs/04.block.md"
git commit -m "Update docs/04.block.md: updated 04.block.md for v3 release"
git add "docs/05.inline.md"
git commit -m "Update docs/05.inline.md: updated 05.inline.md for v3 release"
git add "docs/06.atblock.md"
git commit -m "Update docs/06.atblock.md: updated 06.atblock.md for v3 release"
git add "docs/07.comment.md"
git commit -m "Update docs/07.comment.md: updated 07.comment.md for v3 release"
git add "docs/08.escape.md"
git commit -m "Update docs/08.escape.md: updated 08.escape.md for v3 release"
git add "docs/09.core.md"
git commit -m "Update docs/09.core.md: updated 09.core.md for v3 release"
git add "docs/10.formats.md"
git commit -m "Update docs/10.formats.md: updated 10.formats.md for v3 release"
git add "docs/11.cli.md"
git commit -m "Update docs/11.cli.md: updated 11.cli.md for v3 release"
git add "docs/12.config.md"
git commit -m "Update docs/12.config.md: updated 12.config.md for v3 release"
git add "docs/13.mapper.md"
git commit -m "Update docs/13.mapper.md: updated 13.mapper.md for v3 release"
git add "docs/14.default_mappers.md"
git commit -m "Update docs/14.default_mappers.md: updated 14.default_mappers.md for v3 release"
git add "docs/15.html.md"
git commit -m "Update docs/15.html.md: updated 15.html.md for v3 release"
git add "docs/16.markdown.md"
git commit -m "Update docs/16.markdown.md: updated 16.markdown.md for v3 release"
git add "docs/17.mdx.md"
git commit -m "Update docs/17.mdx.md: updated 17.mdx.md for v3 release"
git add "docs/18.json.md"
git commit -m "Update docs/18.json.md: updated 18.json.md for v3 release"
git add "docs/api/01.outputs.md"
git commit -m "Update docs/api/01.outputs.md: updated 01.outputs.md for v3 release"
git add "docs/api/02.md.md"
git commit -m "Update docs/api/02.md.md: updated 02.md.md for v3 release"
git add "docs/api/03.tag.md"
git commit -m "Update docs/api/03.tag.md: updated 03.tag.md for v3 release"
git add "docs/api/04.get.md"
git commit -m "Update docs/api/04.get.md: updated 04.get.md for v3 release"
git add "docs/api/05.includesId.md"
git commit -m "Update docs/api/05.includesId.md: updated 05.includesId.md for v3 release"
git add "docs/api/06.escapeHtml.md"
git commit -m "Update docs/api/06.escapeHtml.md: updated 06.escapeHtml.md for v3 release"
git add "docs/api/07.register.md"
git commit -m "Update docs/api/07.register.md: updated 07.register.md for v3 release"
git add "docs/api/08.removeOutput.md"
git commit -m "Update docs/api/08.removeOutput.md: updated 08.removeOutput.md for v3 release"
git add "docs/api/09.setHeader.md"
git commit -m "Update docs/api/09.setHeader.md: updated 09.setHeader.md for v3 release"
git add "docs/api/10.pageProps.md"
git commit -m "Update docs/api/10.pageProps.md: updated 10.pageProps.md for v3 release"
git add "docs/api/11.highlightCode.md"
git commit -m "Update docs/api/11.highlightCode.md: updated 11.highlightCode.md for v3 release"
git add "docs/api/12.enable_highlightTheme.md"
git commit -m "Update docs/api/12.enable_highlightTheme.md: updated 12.enable_highlightTheme.md for v3 release"
git add "docs/api/13.registerHighlightTheme.md"
git commit -m "Update docs/api/13.registerHighlightTheme.md: updated 13.registerHighlightTheme.md for v3 release"
git add "docs/api/14.selectHighlightTheme.md"
git commit -m "Update docs/api/14.selectHighlightTheme.md: updated 14.selectHighlightTheme.md for v3 release"
git add "docs/api/15.env.md"
git commit -m "Update docs/api/15.env.md: updated 15.env.md for v3 release"
git add "docs/api/16.enable_table_styles.md"
git commit -m "Update docs/api/16.enable_table_styles.md: updated 16.enable_table_styles.md for v3 release"
git add "docs/api/17.styles.md"
git commit -m "Update docs/api/17.styles.md: updated 17.styles.md for v3 release"
git add "docs/api/18.addStyle.md"
git commit -m "Update docs/api/18.addStyle.md: updated 18.addStyle.md for v3 release"
git add "docs/api/19.header.md"
git commit -m "Update docs/api/19.header.md: updated 19.header.md for v3 release"
git add "docs/api/20.code.md"
git commit -m "Update docs/api/20.code.md: updated 20.code.md for v3 release"
git add "docs/api/21.htmlTable.md"
git commit -m "Update docs/api/21.htmlTable.md: updated 21.htmlTable.md for v3 release"
git add "docs/api/22.parseList.md"
git commit -m "Update docs/api/22.parseList.md: updated 22.parseList.md for v3 release"
git add "docs/api/23.list.md"
git commit -m "Update docs/api/23.list.md: updated 23.list.md for v3 release"
git add "docs/api/24.todo.md"
git commit -m "Update docs/api/24.todo.md: updated 24.todo.md for v3 release"
git add "docs/api/25.safeArg.md"
git commit -m "Update docs/api/25.safeArg.md: updated 25.safeArg.md for v3 release"
git add "docs/api/26.loadCss.md"
git commit -m "Update docs/api/26.loadCss.md: updated 26.loadCss.md for v3 release"
git add "docs/api/27.makeFrontmatter.md"
git commit -m "Update docs/api/27.makeFrontmatter.md: updated 27.makeFrontmatter.md for v3 release"
git add "docs/api/28."
git commit -m "Update docs/api/28.: updated 28. for v3 release"
git add "example.smark"
git commit -m "Update example.smark: updated example.smark for v3 release"
git add "examples/markdown/documentation.smark"
git commit -m "Update examples/markdown/documentation.smark: updated documentation.smark for v3 release"
git add "examples/html/article.smark"
git commit -m "Update examples/html/article.smark: updated article.smark for v3 release"
git add "examples/html/data.smark"
git commit -m "Update examples/html/data.smark: updated data.smark for v3 release"
git add "examples/html/forms.smark"
git commit -m "Update examples/html/forms.smark: updated forms.smark for v3 release"
git add "examples/html/media.smark"
git commit -m "Update examples/html/media.smark: updated media.smark for v3 release"
git add "examples/html/typography.smark"
git commit -m "Update examples/html/typography.smark: updated typography.smark for v3 release"
git add "examples/markdown/tasks.smark"
git commit -m "Update examples/markdown/tasks.smark: updated tasks.smark for v3 release"
git add "formatter/mark.js"
git commit -m "Update formatter/mark.js: updated mark.js for v3 release"
git add "helpers/loadCss.js"
git commit -m "Update helpers/loadCss.js: updated loadCss.js for v3 release"
git add "index.js"
git commit -m "Update index.js: updated index.js for v3 release"
git add "mappers/languages/html.js"
git commit -m "Update mappers/languages/html.js: updated html.js for v3 release"
git add "mappers/languages/markdown.js"
git commit -m "Update mappers/languages/markdown.js: updated markdown.js for v3 release"
git add "mappers/mapper.js"
git commit -m "Update mappers/mapper.js: updated mapper.js for v3 release"
git add "output.html"
git commit -m "Update output.html: updated output.html for v3 release"
git add "smark.config.js"
git commit -m "Update smark.config.js: updated smark.config.js for v3 release"
git add "tests/cli/transpile.test.js"
git commit -m "Update tests/cli/transpile.test.js: updated transpile.test.js for v3 release"
git add "tests/core/ast-access.test.js"
git commit -m "Update tests/core/ast-access.test.js: updated ast-access.test.js for v3 release"
git add "tests/fixtures/header.smark"
git commit -m "Update tests/fixtures/header.smark: updated header.smark for v3 release"
git add "tests/html/full_support.test.js"
git commit -m "Update tests/html/full_support.test.js: updated full_support.test.js for v3 release"
git add "tests/html/html.test.js"
git commit -m "Update tests/html/html.test.js: updated html.test.js for v3 release"
git add "tests/lexer/syntax_compliance.test.js"
git commit -m "Update tests/lexer/syntax_compliance.test.js: updated syntax_compliance.test.js for v3 release"
git add "tests/md/md.test.js"
git commit -m "Update tests/md/md.test.js: updated md.test.js for v3 release"
git add "tests/parser/compliance_edge_cases.test.js"
git commit -m "Update tests/parser/compliance_edge_cases.test.js: updated compliance_edge_cases.test.js for v3 release"
git add "tests/parser/syntax_test.smark"
git commit -m "Update tests/parser/syntax_test.smark: updated syntax_test.smark for v3 release"
git add "tests/plugins/comment-remover.test.js"
git commit -m "Update tests/plugins/comment-remover.test.js: updated comment-remover.test.js for v3 release"
git add "tests/plugins/core.test.js"
git commit -m "Update tests/plugins/core.test.js: updated core.test.js for v3 release"
git add "tests/plugins/highlighting.test.js"
git commit -m "Update tests/plugins/highlighting.test.js: updated highlighting.test.js for v3 release"
git add "tests/plugins/module-system.test.js"
git commit -m "Update tests/plugins/module-system.test.js: updated module-system.test.js for v3 release"
git add "tests/plugins/quote-escaper.test.js"
git commit -m "Update tests/plugins/quote-escaper.test.js: updated quote-escaper.test.js for v3 release"
git add "tests/plugins/rules-validation.test.js"
git commit -m "Update tests/plugins/rules-validation.test.js: updated rules-validation.test.js for v3 release"
git add "tests/test-errors/unclosed_atblock.smark"
git commit -m "Update tests/test-errors/unclosed_atblock.smark: updated unclosed_atblock.smark for v3 release"
git add "tests/text/text.test.js"
git commit -m "Update tests/text/text.test.js: updated text.test.js for v3 release"
git add "v3-todo.smark"
git commit -m "Update v3-todo.smark: updated v3-todo.smark for v3 release"
git add "SOMMARK-SPEC.md"
git commit -m "Update SOMMARK-SPEC.md: updated SOMMARK-SPEC.md for v3 release"
git add "cli/commands/list.js"
git commit -m "Update cli/commands/list.js: updated list.js for v3 release"
git add "commit_all.sh"
git commit -m "Update commit_all.sh: updated commit_all.sh for v3 release"
git add "core/plugins/sommark-format.js"
git commit -m "Update core/plugins/sommark-format.js: updated sommark-format.js for v3 release"
git add "docs/19.plugin-system.md"
git commit -m "Update docs/19.plugin-system.md: updated 19.plugin-system.md for v3 release"
git add "docs/20.built-in-plugins.md"
git commit -m "Update docs/20.built-in-plugins.md: updated 20.built-in-plugins.md for v3 release"
git add "docs/api/11.inherit.md"
git commit -m "Update docs/api/11.inherit.md: updated 11.inherit.md for v3 release"
git add "docs/api/12.clone.md"
git commit -m "Update docs/api/12.clone.md: updated 12.clone.md for v3 release"
git add "docs/api/13.styles.md"
git commit -m "Update docs/api/13.styles.md: updated 13.styles.md for v3 release"
git add "docs/api/14.addStyle.md"
git commit -m "Update docs/api/14.addStyle.md: updated 14.addStyle.md for v3 release"
git add "docs/api/15.header.md"
git commit -m "Update docs/api/15.header.md: updated 15.header.md for v3 release"
git add "docs/api/16.safeArg.md"
git commit -m "Update docs/api/16.safeArg.md: updated 16.safeArg.md for v3 release"
git add "docs/api/17.clear.md"
git commit -m "Update docs/api/17.clear.md: updated 17.clear.md for v3 release"
git add "docs/api/18.getUnknownTag.md"
git commit -m "Update docs/api/18.getUnknownTag.md: updated 18.getUnknownTag.md for v3 release"
git add "docs/api/19.extraProps.md"
git commit -m "Update docs/api/19.extraProps.md: updated 19.extraProps.md for v3 release"
git add "docs/api/20.comment.md"
git commit -m "Update docs/api/20.comment.md: updated 20.comment.md for v3 release"
git add "docs/api/21.formatOutput.md"
git commit -m "Update docs/api/21.formatOutput.md: updated 21.formatOutput.md for v3 release"
git add "docs/api/deprecated-apis.md"
git commit -m "Update docs/api/deprecated-apis.md: updated deprecated-apis.md for v3 release"
git add "examples/html/basic.smark"
git commit -m "Update examples/html/basic.smark: updated basic.smark for v3 release"
git add "examples/html/guides.smark"
git commit -m "Update examples/html/guides.smark: updated guides.smark for v3 release"
git add "examples/html/hub.css"
git commit -m "Update examples/html/hub.css: updated hub.css for v3 release"
git add "examples/html/roadmap.smark"
git commit -m "Update examples/html/roadmap.smark: updated roadmap.smark for v3 release"
git add "examples/html/specification.smark"
git commit -m "Update examples/html/specification.smark: updated specification.smark for v3 release"
git add "format.js"
git commit -m "Update format.js: updated format.js for v3 release"
git add "helpers/utils.js"
git commit -m "Update helpers/utils.js: updated utils.js for v3 release"
git add "unformatted.smark"
git commit -m "Update unformatted.smark: updated unformatted.smark for v3 release"
git add "CHANGELOG.md"
git commit -m "Update CHANGELOG.md: updated CHANGELOG.md for v3 release"
git add "grammar.ebnf"
git commit -m "Update grammar.ebnf: updated grammar.ebnf for v3 release"
git add "examples/markdown/basic.smark"
git commit -m "Update examples/markdown/basic.smark: updated basic.smark for v3 release"