// Token Types in SomMark
const TOKEN_TYPES = {
  OPEN_BRACKET: "OPEN_BRACKET",
  CLOSE_BRACKET: "CLOSE_BRACKET",
  END_KEYWORD: "END_KEYWORD",
  BLOCK_IDENTIFIER: "BLOCK_IDENTIFIER",
  EQUAL: "EQUAL",
  VALUE: "VALUE",
  CONTENT: "CONTENT",
  INLINE_IDENTIFIER: "INLINE_IDENTIFIER",
  THIN_ARROW: "THIN_ARROW",
  OPEN_PAREN: "OPEN_PAREN",
  CLOSE_PAREN: "CLOSE_PAREN",
  AT_IDENTIFIER: "AT_IDENTIFIER",
  OPEN_AT: "OPEN_AT",
  CLOSE_AT: "CLOSE_AT",
  COLON: "COLON",
};

export default TOKEN_TYPES;