import path from "node:path";
import { cliError, formatMessage } from "../../core/errors.js";
import { isExist, createFile } from "../helpers/file.js";

// ========================================================================== //
//  Init Command                                                              //
// ========================================================================== //

/**
 * Initializes a new SomMark configuration file (smark.config.js) in the current directory.
 */
export async function runInit() {
    try {
        const configDir = process.cwd();
        const configFilePath = path.join(configDir, "smark.config.js");

        const defaultConfigContent = `/**
 * SomMark Configuration File
 * Generated by 'smark init'
 */
export default {
    format: "html",           // Target output format (html, markdown, mdx, json, xml)
    removeComments: true,    // Strip SomMark comments from the final output
    customProps: [],         // Whitelisted HTML attributes (prevents CSS hijacking)
    placeholders: {},        // Global p{key} variables for content injection
    outputDir: "./",         // Where to save the transpiled files
    outputFile: "output",    // Default output filename
};
`;

        if (await isExist(configFilePath)) {
            console.log(formatMessage(`<$yellow:Configuration already exists at:$> <$cyan:${configFilePath}$>`));
        } else {
            await createFile(configDir, "smark.config.js", defaultConfigContent);
            console.log(formatMessage(`<$green:Initialized SomMark configuration at:$> <$cyan:${configFilePath}$>`));
        }
    } catch (error) {
        cliError([
            `{line}<$red:Failed to initialize SomMark configuration:$> <$magenta:${error.message}$>{line}`
        ]);
    }
}
