// ###################
// init: create arcmoon.config.js
// ###################

import path from "node:path";
import { isExist, createFile } from "../helpers/file.js";
import { cliError } from "../helpers/errors.js";
import { CONFIG_FILE } from "../constants.js";

const TEMPLATE = `// ###################
// ArcMoon config, generated by "arcmoon init"
// ###################
export default {
	importAliases: { "@": "./src" },   // [import] path aliases
	removeComments: true,              // drop # comments from the HTML
	timeout: 5000,                     // ms for each file's \${ }$ code
	bundle: [],                        // npm packages allowed in runtime code
	outDir: "./dist"                   // where "arcmoon build" writes HTML
};
`;

export async function runInit() {
	const file = path.join(process.cwd(), CONFIG_FILE);
	try {
		if (await isExist(file)) return console.log(`Config already exists: ${file}`);
		await createFile(process.cwd(), CONFIG_FILE, TEMPLATE);
		console.log(`✓ Created ${file}`);
	} catch (err) {
		cliError(`can't create ${CONFIG_FILE}: ${err.message}`);
	}
}
