import path from "node:path";
import { cliError, formatMessage } from "../../core/errors.js";
import { isExist, createFile } from "../helpers/file.js";

// ========================================================================== //
//  Init Command                                                              //
// ========================================================================== //

/**
 * Initializes a new SomMark configuration file (smark.config.js) in the current directory.
 */
export async function runInit() {
    try {
        const configDir = process.cwd();
        const configFilePath = path.join(configDir, "smark.config.js");

        const defaultConfigContent = `/**
 * SomMark Configuration File
 * Generated by 'smark init'
 */
export default {
    format: "html",              // Target output format (html, markdown, mdx, json, xml, jsonc, text)
    removeComments: true,       // Strip SomMark comments from the final output
    generateRuntimeOutput: false, // Generate only VM script bundles, ignoring markup layouts
    hideRuntimeOutput: false,     // Strip all <script> tags from final compiled HTML outputs
    customProps: [],            // Whitelisted HTML attributes
    placeholders: {},           // Global p{key} placeholders for content injection
    importAliases: {            // Custom path aliases for modules (e.g. { "@": "./src/components" })
        "@": "./"
    },
    fallbackTarget: "style",    // Where unrecognized attributes go: "style", "class", or false to disable
    outputValidator: null,      // Custom callback function: async (transpiledOutput) => { ... }
    baseDir: null,              // Base directory for resolving relative module imports
    showSpinner: true,          // Display a dynamic spinner in the terminal during transpilation
    security: {                 // Sandbox and security restrictions for module execution
        allowRaw: true,         // Permit raw code blocks in static logic blocks
        maxDepth: 5,            // Maximum allowed import nesting depth
        timeout: 5000,          // Timeout in milliseconds for scripts to execute
        allowFetch: true,       // Allow fetch queries inside runtime logic block execution
        allowHttp: false,       // Disallow http requests (highly recommended to keep false)
        allowedOrigins: [],     // Whitelisted HTTP origins/domains for fetch requests (e.g. ["api.github.com"])
        allowedExtensions: [],  // Whitelisted file extensions for local module imports (e.g. [".smark", ".json"])
        sanitize: null,         // Custom output HTML string sanitization function: (html) => { ... }
    },
    outputDir: "./",            // Where to save the transpiled files
    outputFile: "output",       // Default output filename
};
`;

        if (await isExist(configFilePath)) {
            console.log(formatMessage(`<$yellow:Configuration already exists at:$> <$cyan:${configFilePath}$>`));
        } else {
            await createFile(configDir, "smark.config.js", defaultConfigContent);
            console.log(formatMessage(`<$green:Initialized SomMark configuration at:$> <$cyan:${configFilePath}$>`));
        }
    } catch (error) {
        cliError([
            `{line}<$red:Failed to initialize SomMark configuration:$> <$magenta:${error.message}$>{line}`
        ]);
    }
}
