import { describe, it, expect } from "vitest";
import SomMark, { transpile } from "../../index.js";

describe("Plugin System: Core Functionality", () => {
    const testPlugins = [
        {
            name: "TopLevelPreprocessor",
            type: "preprocessor",
            scope: "top-level",
            beforeLex(src) {
                return src.replace(/\[\[IMPORT\]\]/g, "[Section]Imported content[end]");
            }
        },
        {
            name: "ArgPreprocessor",
            type: "preprocessor",
            scope: "arguments",
            beforeLex(args) {
                return args.replace(/@blue/g, "color:blue");
            }
        },
        {
            name: "ContentPreprocessor",
            type: "preprocessor",
            scope: "content",
            beforeLex(content) {
                return content.replace(/!!HI!!/g, "Hello World from Plugin");
            }
        },
        {
            name: "CustomTag",
            type: "mapper",
            outputs: [
                {
                    id: "Alert",
                    register({ args, content }) {
                        const type = args[0] || "info";
                        return `<div class="alert alert-${type}">${content}</div>`;
                    }
                }
            ]
        },
        {
            name: "TailwindSupport",
            type: "mapper",
            rules: {
                recognizedArguments: ["class"]
            }
        },
        {
            name: "FooterTransformer",
            type: "transform",
            transform(html) {
                return html + "\n<footer>Generated by Plugin System</footer>";
            }
        }
    ];

    const src = `
[[IMPORT]]

[Section = class:bg-blue-500, @blue, type:modern]
!!HI!!
[end]

[Alert = warning]
This is a custom alert
[end]
`;

    it("verifies all plugin types and scopes", async () => {
        const result = await transpile({
            src,
            format: "html",
            plugins: testPlugins,
            includeDocument: false
        });

        // Check Top-Level Preprocessor
        expect(result).toMatch(/<section>Imported content<\/section>|Imported content/);

        // Check Arg Preprocessor
        expect(result).toContain("color:blue");

        // Check Content Preprocessor
        expect(result).toContain("Hello World from Plugin");

        // Check Custom Tag
        expect(result).toContain('class="alert alert-warning"');

        // Check Transformer
        expect(result).toContain("<footer>Generated by Plugin System</footer>");

        // Check Recognized Argument
        expect(result).toContain('class="bg-blue-500"');
    });

    it("allows excluding built-in plugins", async () => {
        // By default quote-escaper is active.
        const src = '[Section = class:"hover:bg-blue-500"]Content[end]';
        
        // With quote-escaper (default)
        const resultWith = await transpile({ src, format: "html", includeDocument: false });
        expect(resultWith).toContain('class="hover:bg-blue-500"');

        // Excluding quote-escaper causes LexerError because quotes are not allowed in keys
        await expect(transpile({ 
            src, 
            format: "html", 
            includeDocument: false,
            excludePlugins: ["quote-escaper"]
        })).rejects.toContain("[Lexer Error]");
    });
});
