import TOKEN_TYPES from "../core/tokenTypes.js";
const blockType1 = [
  TOKEN_TYPES.OPEN_BRACKET,
  TOKEN_TYPES.IDENTIFIER,
  TOKEN_TYPES.EQUAL,
  TOKEN_TYPES.VALUE,
  TOKEN_TYPES.CLOSE_BRACKET,
];

const blockType2 = [
  TOKEN_TYPES.OPEN_BRACKET,
  TOKEN_TYPES.IDENTIFIER,
  TOKEN_TYPES.CLOSE_BRACKET,
];

const inlineType = [
  TOKEN_TYPES.OPEN_PAREN,
  TOKEN_TYPES.VALUE,
  TOKEN_TYPES.CLOSE_PAREN,
  TOKEN_TYPES.THIN_ARROW,
  TOKEN_TYPES.OPEN_PAREN,
  TOKEN_TYPES.IDENTIFIER,
  TOKEN_TYPES.CLOSE_PAREN,
];

const atType1 = [
  TOKEN_TYPES.OPEN_AT,
  TOKEN_TYPES.IDENTIFIER,
  TOKEN_TYPES.CLOSE_AT,
  TOKEN_TYPES.COLON,
  TOKEN_TYPES.VALUE,
];

const atType2 = [
  TOKEN_TYPES.OPEN_AT,
  TOKEN_TYPES.IDENTIFIER,
  TOKEN_TYPES.CLOSE_AT,
];

const endType1 = [
  TOKEN_TYPES.OPEN_BRACKET,
  TOKEN_TYPES.END_KEYWORD,
  TOKEN_TYPES.CLOSE_BRACKET,
];

const endType2 = [
  TOKEN_TYPES.OPEN_AT,
  TOKEN_TYPES.END_KEYWORD,
  TOKEN_TYPES.CLOSE_AT,
];

export { blockType1, blockType2, inlineType, atType1, atType2, endType1, endType2 };
